/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author owner
 */
public class Acccommodation extends javax.swing.JFrame  {

    /**
     * Creates new form Acccommodation
     */
    
    
    Connection conn;
    Statement st;
    ResultSet rs;
    PreparedStatement pst;
    
    String url = "jdbc:mysql://localhost:3306/hoteldb";
    String username = "root";
    String password = "";
    
   //String url = "jdbc:mysql://localhost:3306/hoteldb";
    
    public Acccommodation()  {
        initComponents();
        loadicon();
        disableupdatedelete();
        
    }
    void loadicon(){
    ImageIcon icon = new ImageIcon();
    icon = new ImageIcon("Images/logo.png");
    setIconImage(icon.getImage());
    }
    void disableupdatedelete(){
    btndelete.setEnabled(false);
    btnupdate.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnaddnew = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtnewregion = new javax.swing.JTextField();
        cmbregion = new javax.swing.JComboBox<>();
        cmbcategory = new javax.swing.JComboBox<>();
        txtprice = new javax.swing.JTextField();
        txtmeal = new javax.swing.JTextField();
        txt2maels = new javax.swing.JTextField();
        txt3meals = new javax.swing.JTextField();
        txtdiscount = new javax.swing.JTextField();
        btndelete = new javax.swing.JButton();
        btnaccommodationback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ACCOMMODATION");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 103, 7));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel1.setText("LUXURT HOTEL    ACCOMMODATION CONTROL");

        jPanel2.setBackground(new java.awt.Color(240, 177, 68));

        jLabel2.setText("SELECT REGION");

        jLabel3.setText("SELECT ROOM  TYPE");

        jLabel4.setText("NET ROOM PRICE");

        jLabel5.setText("1 MEAL SLOT");

        jLabel6.setText("2 MEALS SLOT");

        jLabel7.setText("3 MEALS SLOT");

        jLabel8.setText("DISCOUNT");

        btnsave.setText("SAVE PRICE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnaddnew.setText("ADD NEW");

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        jLabel9.setText("ADD NEW REGION");

        cmbregion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAIROBI", "KISUMU", "ELDORET", "MOMBASA" }));

        cmbcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRIDE", "LUXURY", "PRESIDENTIAL" }));
        cmbcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcategoryActionPerformed(evt);
            }
        });

        btndelete.setText("DELETE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnsave)
                        .addGap(18, 18, 18)
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnaddnew, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnewregion)
                            .addComponent(txtdiscount)
                            .addComponent(txt3meals)
                            .addComponent(txt2maels)
                            .addComponent(txtmeal)
                            .addComponent(txtprice)
                            .addComponent(cmbcategory, 0, 151, Short.MAX_VALUE)
                            .addComponent(cmbregion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbregion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt2maels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt3meals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtnewregion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddnew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnaccommodationback.setBackground(new java.awt.Color(255, 255, 255));
        btnaccommodationback.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        btnaccommodationback.setForeground(new java.awt.Color(0, 0, 153));
        btnaccommodationback.setText("BACK");
        btnaccommodationback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccommodationbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnaccommodationback))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaccommodationback, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {
            // TODO add your handling code here:

            conn = DriverManager.getConnection(url, username, password);
            st = conn.createStatement();
            String sqlupdate = "UPDATE tblroomspricing set NETPRICE= '"+txtprice.getText()+"',MEAL = '"+txtmeal.getText()+"',TWOMEALS"
                    + "= '"+txt2maels.getText()+"',THREEMALES= '"+txt3meals.getText()+"',DISCOUNT= '"+txtdiscount.getText()+"' "
                    + "WHERE REGION = ? && CATEGORY= '"+cmbcategory.getSelectedItem()+"' ";
            pst = conn.prepareStatement(sqlupdate);
            pst.setString(1, (String) cmbregion.getSelectedItem());
            pst.executeUpdate();
            String reg = (String)cmbregion.getSelectedItem(); 
        String cat = (String)cmbcategory.getSelectedItem();
        String mesg =" "+reg+ " REGION "+ " " +cat+ " PRICE UPDATED";
        JOptionPane.showMessageDialog(null,mesg);
        btnsave.setEnabled(true);
        txtprice.setText("");
        txtmeal.setText("");
        txt2maels.setText("");
        txt3meals.setText("");
        txtdiscount.setText("");
        
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
       
        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnaccommodationbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccommodationbackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Admin().setVisible(true);
    }//GEN-LAST:event_btnaccommodationbackActionPerformed

    private void cmbcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcategoryActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        try{
        conn = DriverManager.getConnection(url, username, password);
        st = conn.createStatement();
        String sqlsave = "INSERT INTO tblroomspricing(REGION,CATEGORY,NETPRICE,MEAL,TWOMEALS,THREEMALES,DISCOUNT) VALUES "
                + "('"+cmbregion.getSelectedItem()+"','"+cmbcategory.getSelectedItem()+"','"+txtprice.getText()+"','"+txtmeal.getText()+"',"
                + "'"+txt2maels.getText()+"','"+txt3meals.getText()+"','"+txtdiscount.getText()+"')";
        if(!"".equals(txtprice.getText())&& !"".equals(txtmeal.getText())&& !"".equals(txt2maels.getText())&& !"".equals(txt3meals.getText())
                &&!"".equals(txtdiscount.getText())){
        st.execute(sqlsave);
        String reg = (String)cmbregion.getSelectedItem(); 
        String cat = (String)cmbcategory.getSelectedItem();
        String mesg =" "+reg+ " REGION "+ " " +cat+ " NEW  PRICE SAVED";
        JOptionPane.showMessageDialog(null,mesg);
        txtprice.setText("");
        txtmeal.setText("");
        txt2maels.setText("");
        txt3meals.setText("");
        txtdiscount.setText("");
        }else{
        String reg = (String)cmbregion.getSelectedItem(); 
        String cat = (String)cmbcategory.getSelectedItem();
        String mesg =" "+reg+ " REGION "+ " " +cat+ " ENTER ALL FIELDS ??? ";
        JOptionPane.showMessageDialog(null,mesg);
        }
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        try{
        conn = DriverManager.getConnection(url,username,password);
        st = conn.createStatement();
        String sqlsearch = "SELECT * FROM tblroomspricing WHERE REGION = ? && CATEGORY= '"+cmbcategory.getSelectedItem()+"' ";
        pst = conn.prepareStatement(sqlsearch);
        pst.setString(1,(String) cmbregion.getSelectedItem());
        
        rs=pst.executeQuery();
        if(rs.next()){
        JOptionPane.showMessageDialog(null, "selected");
        String regn = rs.getString("REGION");
        cmbregion.setSelectedItem(regn);
        String cat = rs.getString("CATEGORY");
        cmbregion.setSelectedItem(cat);
        String price = rs.getString("NETPRICE");
        txtprice.setText(price);
        String meal = rs.getString("MEAL");
        txtmeal.setText(meal);
        String tmeal = rs.getString("TWOMEALS");
        txt2maels.setText(tmeal);
        String trmeal = rs.getString("THREEMALES");
        txt3meals.setText(trmeal);
        String discount = rs.getString("DISCOUNT");
        txtdiscount.setText(discount);
        
        //enable save button
         btndelete.setEnabled(true);
         btnupdate.setEnabled(true);
         btnsave.setEnabled(false);
        }else{
        JOptionPane.showMessageDialog(null, "<HTML><b style=\"color: red; font-size: 24px;\">no item found</b></HTML>");
        }
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acccommodation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acccommodation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acccommodation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acccommodation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acccommodation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaccommodationback;
    private javax.swing.JButton btnaddnew;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cmbcategory;
    private javax.swing.JComboBox<String> cmbregion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt2maels;
    private javax.swing.JTextField txt3meals;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txtmeal;
    private javax.swing.JTextField txtnewregion;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
