/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;


/**
 *
 * @author owner
 */
public class Accommodatiocontrol extends javax.swing.JFrame {

    /**
     * Creates new form Accommodatiocontrol
     */
    
    
    Connection conn;
    Statement st;
    ResultSet rs;
    PreparedStatement pst;
    
    String url = "jdbc:mysql://localhost:3306/hoteldb";
    String username = "root";
    String password = "";
    
    java.sql.Date din,dout;
    java.util.Date checkin,checkout;
    public Accommodatiocontrol() {
        initComponents();
        loadicon();
        showdate();
        showtime();
        disablebuttons();
    }
        void loadicon(){
    ImageIcon icon = new ImageIcon();
    icon = new ImageIcon("Images/logo.png");
    setIconImage(icon.getImage());
    }
         void showdate(){
    Date d = new Date();
    SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
    lbdate.setText("Date :"+s.format(d));
    
    }
     void showtime(){
          new Timer (0, new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent ae) {
                 //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
             
                 Date d = new Date();
    SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
    lbtime.setText("Time :"+s.format(d));
    
             }
         }){
             
         }.start();
    
    }
     
     void disablebuttons(){
     
     btnsavereservation.setEnabled(false);
     btnprintreceipt.setEnabled(false);
     btncheckrates.setEnabled(false);
     
      
     txtphone.setEnabled(false);
     txtemail.setEnabled(false);
     txtid.setEnabled(false);
     txtperiod.setEnabled(false);
     txtdiscount.setEnabled(false);
     txtcost.setEnabled(false);
     txtnetprice.setEnabled(false);
     txtmealslot.setEnabled(false);
     spchildrenroom.setEnabled(false);
     spadultsroom.setEnabled(false);
     jdcheckin.setEnabled(false);
     jdcheckout.setEnabled(false);
     
     
     tareceipt.setEditable(false);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnapprovebook = new javax.swing.JButton();
        btnclearclient = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbregion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbcategory = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        spadultsroom = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        spchildrenroom = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jdcheckin = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jdcheckout = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcost = new javax.swing.JTextField();
        txtdiscount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtnetprice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        btnaddreservation = new javax.swing.JButton();
        btnsavereservation = new javax.swing.JButton();
        btncheckrates = new javax.swing.JButton();
        btnprintreceipt = new javax.swing.JButton();
        jpreceipt = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lbdate = new javax.swing.JLabel();
        lbtime = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tareceipt = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtmealslot = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtperiod = new javax.swing.JTextField();
        btnlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ACCOMMODATION  CONTROL");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 81, 6));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        jLabel1.setText("LUXURY HOTEL ACCOMMODATION ALLOCATION");

        jPanel2.setBackground(new java.awt.Color(240, 164, 52));

        jPanel3.setBackground(new java.awt.Color(240, 81, 6));

        jLabel2.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ACTION MENU");

        btnapprovebook.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        btnapprovebook.setText("APPROVE BOOK");
        btnapprovebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapprovebookActionPerformed(evt);
            }
        });

        btnclearclient.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        btnclearclient.setText("CLEAR CLIENT");
        btnclearclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearclientActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        jButton4.setText("CANCEL BOOK");
        jButton4.setToolTipText("");

        jButton5.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        jButton5.setText("REPORTS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnclearclient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnapprovebook)
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(btnapprovebook, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnclearclient, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("REGION");

        cmbregion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAOROBI", "KISUMU", "ELDORET", "MOMBASA" }));

        jLabel4.setText("ROOM CATEGORY");

        cmbcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRIDE", "LUXURY", "PRESIDENTIAL" }));

        jLabel5.setText("ADULT ROOMS");

        jLabel6.setText("JUNOR ROOMS");

        jLabel7.setText("CEHCK IN ");

        jdcheckin.setDateFormatString("dd-MM-yyyy");

        jLabel8.setText("CHECK OUT");

        jdcheckout.setDateFormatString("dd-MM-yyyy");

        jLabel9.setText("TOTAL COST");

        jLabel10.setText("DISCOUNT");

        jLabel11.setText("NET  COST");

        jLabel12.setText("ID NUMBER");

        jLabel13.setText("PHONE");

        jLabel14.setText("EMAIL");

        btnaddreservation.setText("ADD RESERVATION");
        btnaddreservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddreservationActionPerformed(evt);
            }
        });

        btnsavereservation.setText("SAVE RESERVATION");
        btnsavereservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavereservationActionPerformed(evt);
            }
        });

        btncheckrates.setText("CHECK RATES");
        btncheckrates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckratesActionPerformed(evt);
            }
        });

        btnprintreceipt.setText("PRINT RECEIPT");
        btnprintreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintreceiptActionPerformed(evt);
            }
        });

        jpreceipt.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setText("LUXURY HOTEL  ACCOMMODATION");

        lbdate.setText("DATE");

        lbtime.setText("TIME");

        jLabel19.setText("PO BOX 0001-3006    ELDORET");

        jLabel20.setFont(new java.awt.Font("Felix Titling", 0, 11)); // NOI18N
        jLabel20.setText("THANK FOR YOUR VISIT ");

        jLabel21.setFont(new java.awt.Font("Felix Titling", 0, 11)); // NOI18N
        jLabel21.setText("WELCOME AGAIN");

        tareceipt.setColumns(20);
        tareceipt.setRows(5);
        jScrollPane2.setViewportView(tareceipt);

        javax.swing.GroupLayout jpreceiptLayout = new javax.swing.GroupLayout(jpreceipt);
        jpreceipt.setLayout(jpreceiptLayout);
        jpreceiptLayout.setHorizontalGroup(
            jpreceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpreceiptLayout.createSequentialGroup()
                .addGroup(jpreceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpreceiptLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel16))
                    .addGroup(jpreceiptLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbdate)
                        .addGap(18, 18, 18)
                        .addComponent(lbtime))
                    .addGroup(jpreceiptLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19))
                    .addGroup(jpreceiptLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20))
                    .addGroup(jpreceiptLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jpreceiptLayout.setVerticalGroup(
            jpreceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpreceiptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpreceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbdate)
                    .addComponent(lbtime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("RECEIPT");

        jLabel17.setText("MEAL SLOT");

        jLabel18.setText("PERIOD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel8)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbregion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbcategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spadultsroom)
                            .addComponent(spchildrenroom)
                            .addComponent(jdcheckin, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jdcheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcost)
                            .addComponent(txtdiscount)
                            .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtphone, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtmealslot)
                            .addComponent(txtnetprice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtperiod))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel15))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jpreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnaddreservation)
                        .addGap(18, 18, 18)
                        .addComponent(btnsavereservation, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncheckrates)
                        .addGap(18, 18, 18)
                        .addComponent(btnprintreceipt)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbregion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(spadultsroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(spchildrenroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jdcheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jdcheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtmealslot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtnetprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtperiod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jpreceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddreservation, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsavereservation, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncheckrates, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprintreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        btnlogout.setBackground(new java.awt.Color(255, 255, 255));
        btnlogout.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 0, 0));
        btnlogout.setText("LOGOUT");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlogout)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnapprovebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapprovebookActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Aprovebookings().setVisible(true);
    }//GEN-LAST:event_btnapprovebookActionPerformed

    private void btnclearclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearclientActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Clearaccommodation().setVisible(true);
    }//GEN-LAST:event_btnclearclientActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnprintreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintreceiptActionPerformed
        // TODO add your handling code here:
         PrinterJob pjob = PrinterJob.getPrinterJob();
            pjob.setJobName("SALE RECEIPT");
            pjob.setPrintable(new Printable(){ 
            public int print(Graphics pg ,PageFormat pf, int pagenum){
            pf.setOrientation(PageFormat.LANDSCAPE);
            if(pagenum > 0){
            return Printable.NO_SUCH_PAGE;
            }
            java.awt.Graphics2D g2 = (java.awt.Graphics2D)pg;
            g2.translate(pf.getImageableX(), pf.getImageableY());
            g2.scale(0.63, 0.97);
            jpreceipt.paint(g2);
            return Printable.PAGE_EXISTS;
            }
            });
            boolean  ok = pjob.printDialog();
            if(ok){
            try{
            pjob.print();
             
     //btnprintreceipt.setEnabled(false);
     
            }catch(PrinterException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            }
    }//GEN-LAST:event_btnprintreceiptActionPerformed

    private void btnaddreservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddreservationActionPerformed
        // TODO add your handling code here:
        
        
        txtphone.setEnabled(true);
     txtemail.setEnabled(true);
     txtid.setEnabled(true);
     txtmealslot.setEnabled(true);
     spchildrenroom.setEnabled(true);
     spadultsroom.setEnabled(true);
     jdcheckin.setEnabled(true);
     jdcheckout.setEnabled(true);
        
        
        
        
       btnsavereservation.setEnabled(true);
     btnprintreceipt.setEnabled(true);
     btncheckrates.setEnabled(true);
     tareceipt.setText("");
     txtphone.setText("");
     txtemail.setText("@gmail.com");
     txtid.setText("");
     txtperiod.setText("");
     txtdiscount.setText("");
     txtcost.setText("");
     txtnetprice.setText("");
     int slot = 0;
     txtmealslot.setText(""+slot);
     spchildrenroom.setValue(slot);
     spadultsroom.setValue(slot);
     jdcheckin.setDate(checkin);
     jdcheckout.setDate(checkout);
     
    }//GEN-LAST:event_btnaddreservationActionPerformed

    private void btnsavereservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavereservationActionPerformed
        // TODO add your handling code here:
        try{
       
       
       if(!"".equals(txtid.getText()) && !"".equals(txtphone.getText()) && !"".equals(txtperiod.getText()) && !"".equals(txtcost.getText()) && 
               !"".equals(txtdiscount.getText()) && !"".equals(txtnetprice.getText()) && !"".equals(txtid.getText())){
           
            String region = (String)cmbregion.getSelectedItem();
        String category  = (String) cmbcategory.getSelectedItem();
       int adultroom = (int) spadultsroom.getValue();
       int childernroom = (int) spchildrenroom.getValue();
       int totalrooms = adultroom + childernroom;
       checkin = jdcheckin.getDate();
       din = new java.sql.Date(checkin.getTime());
       checkout = jdcheckout.getDate();
       String idnumber = txtid.getText();
       String phone= txtphone.getText();
       String period = txtperiod.getText();
       String mealslot = txtmealslot.getText();
       String email = txtemail.getText();
       String cost = txtcost.getText();
       double sqlcost = Double.parseDouble(cost);
       String discount = txtdiscount.getText();
       String netpay = txtnetprice.getText();
       dout = new java.sql.Date(checkout.getTime());
       String status = "ALLOCATED ROOM";
       tareceipt.setText("REGION  : "+region+"\n"+ "CATEGORY :  " +category+ "\n"+ "ADULTS ROOMS :"+adultroom+"\n"+
               "CHILDEN  ROOMS :  "+childernroom+"\n"+"CHECK IN : "+din+"\n"+"CHECK OUT :"+dout +"\n"+ "ID NUMBER :  " +idnumber+ "\n"+
                       "PHONE NO  :  " +phone+ "\n" +"Email  :  " +email+"\n"+"ACCOMMODATION DAYS: "+period+"\n"+"MEAL SLOTS : "+mealslot+ "\n"+"\n"+ "TOTAL COST:  "+"  Ksh " +cost+ "\n"+ "DISCOUNT  :  " +"  Ksh "  +discount+
               "\n"+ "NET PAY  " +"  Ksh "  +netpay);
           
           
       conn = DriverManager.getConnection(url,username,password);
       st = conn.createStatement();
       String sqlsave = "INSERT INTO tblaccommodation(IDNUMBER,REGION,CATEGORY,TOTALROOMS,ADULTSROOM,JUNOIRROOMS,CHECKIN,CHECKOUT,PERIOD,MEALSLOT,TOTALPAY,"
               + "DISCOUNT,NETPAY,PHONE,EMAIL,STATUS) VALUES ('"+txtid.getText()+"','"+cmbregion.getSelectedItem()+"','"+cmbcategory.getSelectedItem()+"','"+totalrooms+"',"
               + "'"+adultroom+"','"+childernroom+"','"+din+"','"+dout+"','"+txtperiod.getText()+"','"+mealslot+"','"+sqlcost+"','"+discount+"','"+netpay+"',"
               + "'"+txtphone.getText()+"','"+txtemail.getText()+"','"+status+"')";
       st.execute(sqlsave);
       JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 16px;\">Reservation Added </i></HTML>");
        btnsavereservation.setEnabled(false);
     
     btncheckrates.setEnabled(false);
       }else{
       JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: #F05106; font-size: 16px;\">Fill in all client data!!!</i></HTML>");
       }
         
        }
        catch(HeadlessException  | SQLException ex){
        
        
        JOptionPane.showMessageDialog(null,ex);
        } catch(NumberFormatException ne){
        JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: #F05106; font-size: 16px;\">Fill in all client data!!!</i></HTML>");
        }
        
        
    }//GEN-LAST:event_btnsavereservationActionPerformed

    private void btncheckratesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckratesActionPerformed
        // TODO add your handling code here:
        try{
            conn = DriverManager.getConnection(url,username,password);
            st = conn.createStatement();
           String sqlsearch = "SELECT * FROM tblroomspricing WHERE REGION = ? && CATEGORY= '"+cmbcategory.getSelectedItem()+"' ";
        pst = conn.prepareStatement(sqlsearch);
        pst.setString(1,(String) cmbregion.getSelectedItem());
        
        rs=pst.executeQuery();
        if(rs.next()){
        JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 16px;\">Processing Requist ...</i></HTML>");
        String regn = rs.getString("REGION");
        cmbregion.setSelectedItem(regn);
        String cat = rs.getString("CATEGORY");
        cmbregion.setSelectedItem(cat);
        String price = rs.getString("NETPRICE");
        int p = Integer.parseInt(price);
        String meal = rs.getString("MEAL");
        int m1 = Integer.parseInt(meal);
        
        String tmeal = rs.getString("TWOMEALS");
        int m2 = Integer.parseInt(tmeal);
        String trmeal = rs.getString("THREEMALES");
        int m3 = Integer.parseInt(trmeal);
        String discount = rs.getString("DISCOUNT");
        int dis = Integer.parseInt(discount);
        
        //get difference in days 
        Date start = jdcheckin.getDate();
        Date end = jdcheckout.getDate(); 
        long diffInMillies = Math.abs(end.getTime() - start.getTime());
        long diff = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);
        txtperiod.setText(String.valueOf(+diff));
        // get all the variables for calculation
        String mslot = txtmealslot.getText();
        int mealslot = Integer.parseInt(mslot);
        String speriod = txtperiod.getText();
        int period = Integer.parseInt(speriod);
      int adultrnumer = (int)spadultsroom.getValue();
      int childrenrnumer = (int)spchildrenroom.getValue();
      int totalrooms = adultrnumer + childrenrnumer;
     
      
      // calculation
      if(mealslot < 1){
          
          
          double cost = (totalrooms * p * period);
          double discal = (totalrooms * p * period)*(dis*0.01);
      double totalcost = (totalrooms * p * period)-discal; 
      txtcost.setText(""+cost);
      txtdiscount.setText(""+ discal);
      txtnetprice.setText("" + totalcost);
      System.out.println(discal);
      }else if(mealslot == 1){
      
      double meals = totalrooms * m1 * period;
      double cost = (totalrooms * p * period)+meals;
          double discal = (cost)* (dis*0.01);
      double totalcost = (totalrooms * p * period)+ meals -discal; 
      txtcost.setText(""+cost);
      txtdiscount.setText(""+discal);
      txtnetprice.setText(""+totalcost);
      
      }else if (mealslot == 2){
      
      double meals = totalrooms * m2 * period;
      double cost = (totalrooms * p * period)+meals;
          double discal = (totalrooms * p * period)*(dis*0.01);
      double totalcost = (totalrooms * p * period)+ meals -discal; 
      txtcost.setText(""+cost);
      txtdiscount.setText(""+ discal);
      txtnetprice.setText("" + totalcost);
      }else if  (mealslot == 3){
      
      double meals = totalrooms * m3 * period;
      double cost = (totalrooms * p * period)+meals;
          double discal = (totalrooms * p * period)*(dis*0.01);
      double totalcost = (totalrooms * p * period)+ meals -discal; 
      txtcost.setText(""+cost);
      txtdiscount.setText(""+ discal);
      txtnetprice.setText("" + totalcost);
      }else{
      JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: blue; font-size: 16px;\">CHECK MEAL SLOT</i></HTML>");
      }
      
        }else{
        JOptionPane.showMessageDialog(null, "<HTML><b style=\"color: red; font-size: 16px;\">no item found</b></HTML>");
        }
        
        }catch(HeadlessException  | SQLException ex){
            JOptionPane.showMessageDialog(null,ex );
        } catch(NumberFormatException nx){
            JOptionPane.showMessageDialog(null,"<HTML><b style=\"color: brown; font-size: 16px;\">Enter Meal Slot !!!</b></HTML>");
        }catch (NullPointerException npe){
        JOptionPane.showMessageDialog(null,"<HTML><b style=\"color: brown; font-size: 16px;\">Enter Dates!!!</b></HTML>");
        }
    }//GEN-LAST:event_btncheckratesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accommodatiocontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accommodatiocontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accommodatiocontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accommodatiocontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accommodatiocontrol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddreservation;
    private javax.swing.JButton btnapprovebook;
    private javax.swing.JButton btncheckrates;
    private javax.swing.JButton btnclearclient;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnprintreceipt;
    private javax.swing.JButton btnsavereservation;
    private javax.swing.JComboBox<String> cmbcategory;
    private javax.swing.JComboBox<String> cmbregion;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdcheckin;
    private com.toedter.calendar.JDateChooser jdcheckout;
    private javax.swing.JPanel jpreceipt;
    private javax.swing.JLabel lbdate;
    private javax.swing.JLabel lbtime;
    private javax.swing.JSpinner spadultsroom;
    private javax.swing.JSpinner spchildrenroom;
    private javax.swing.JTextArea tareceipt;
    private javax.swing.JTextField txtcost;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmealslot;
    private javax.swing.JTextField txtnetprice;
    private javax.swing.JTextField txtperiod;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
