/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotelmanagement;

/**
 *
 * @author owner
 */
public class Login extends javax.swing.JFrame {

    /** Creates new form Login */
    public Login() {
        initComponents();
        hideregister ();
    }
    
    
    void hideregister (){
    lbeno.setVisible(false);
    lbcpassword.setVisible(false);
    txteno.setVisible(false);
    jcpassword.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtusername = new javax.swing.JTextField();
        jpassword = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        btnreg = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        lbusername = new javax.swing.JLabel();
        lbpassword = new javax.swing.JLabel();
        lbcpassword = new javax.swing.JLabel();
        jcpassword = new javax.swing.JPasswordField();
        lbeno = new javax.swing.JLabel();
        txteno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(665, 385));
        setPreferredSize(new java.awt.Dimension(665, 385));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 87, 2));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(240, 159, 37));
        jPanel2.setPreferredSize(new java.awt.Dimension(670, 340));
        jPanel2.setLayout(null);
        jPanel2.add(txtusername);
        txtusername.setBounds(290, 60, 200, 30);
        jPanel2.add(jpassword);
        jpassword.setBounds(290, 100, 200, 30);

        btnlogin.setBackground(new java.awt.Color(102, 255, 102));
        btnlogin.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        btnlogin.setText("LOGIN");
        jPanel2.add(btnlogin);
        btnlogin.setBounds(170, 200, 140, 40);

        btnreg.setBackground(new java.awt.Color(102, 255, 204));
        btnreg.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        btnreg.setText("REGISTER");
        btnreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregActionPerformed(evt);
            }
        });
        jPanel2.add(btnreg);
        btnreg.setBounds(330, 200, 210, 40);

        btnexit.setBackground(new java.awt.Color(255, 255, 255));
        btnexit.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        btnexit.setForeground(new java.awt.Color(0, 51, 204));
        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel2.add(btnexit);
        btnexit.setBounds(490, 250, 160, 30);

        lbusername.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        lbusername.setText("USERNAME");
        jPanel2.add(lbusername);
        lbusername.setBounds(140, 70, 150, 13);

        lbpassword.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        lbpassword.setText("PASSWORD");
        jPanel2.add(lbpassword);
        lbpassword.setBounds(140, 110, 140, 13);

        lbcpassword.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        lbcpassword.setText("CONFIRM PASSWORD");
        jPanel2.add(lbcpassword);
        lbcpassword.setBounds(70, 140, 270, 20);
        jPanel2.add(jcpassword);
        jcpassword.setBounds(290, 140, 200, 30);

        lbeno.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        lbeno.setText("EMPLOYEMENT NO");
        jPanel2.add(lbeno);
        lbeno.setBounds(90, 30, 200, 20);
        jPanel2.add(txteno);
        txteno.setBounds(290, 20, 200, 30);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(190, 20, 280, 290);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 60, 670, 340);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel1.setText("LUXURY   HOTEL  LOGIN/ACCOUNT CREATION ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 640, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
       this.dispose();
       new Dashboard().setVisible(true);
       
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregActionPerformed
        // TODO add your handling code here:
        lbeno.setVisible(true);
    lbcpassword.setVisible(true);
    txteno.setVisible(true);
    jcpassword.setVisible(true);
    btnreg.setText("SUBMIT NOW");
    }//GEN-LAST:event_btnregActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnreg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jcpassword;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JLabel lbcpassword;
    private javax.swing.JLabel lbeno;
    private javax.swing.JLabel lbpassword;
    private javax.swing.JLabel lbusername;
    private javax.swing.JTextField txteno;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables

}
