/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import java.awt.HeadlessException;
import javax.swing.ImageIcon;

/**
 *
 * @author owner
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class Meals extends javax.swing.JFrame {

    /**
     * Creates new form Meals
     */
    String url = "jdbc:mysql://localhost:3306/hoteldb";
        String username = "root";
        String password = "";
    
    
    public Meals() {
        initComponents();
        loadicon();
    }
     private Connection conn ;
     private Statement st;
     private ResultSet rs;
     private PreparedStatement pst;
    void loadicon(){
    ImageIcon icon = new ImageIcon();
    icon = new ImageIcon("Images/logo.png");
    setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbmealitem = new javax.swing.JComboBox<>();
        txtpricemeal = new javax.swing.JTextField();
        txtdiscountmeals = new javax.swing.JTextField();
        txtnewmeal = new javax.swing.JTextField();
        btnsaveprice = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnmealback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LUXURY HOTEL  MEALS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 79, 9));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel1.setText("LUXURY  HOTEL MEALS CONTROL");

        jPanel2.setBackground(new java.awt.Color(240, 132, 34));

        jLabel2.setText("SELECT MEAL ITEM");

        jLabel3.setText("DISCOUNT ALLOWED");

        jLabel4.setText("NET  PRICE");

        jLabel5.setText("NEW ITEM");

        cmbmealitem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEA", "COFFEE", "COCOA", "BLACK TEA", "CHOCOLATE", "MILK", "BREAD", "MAFFIN", "SCONS", "QUEEN CAKE", "PAN CAKE", "TOST", "COOKIES", "MARIANDAZI", "CHAPO", "UGALI", "RICE", "POTATOES", "BANANAS", "PITZA", "SHEDERS", "CHIPS", "FISH", "BEEF FRY", "BEEF CHOMA", "POCK", "CHICKEN", "CABBAGE", "KALES", "MANGO", "ORANGE", "BANANAS", "PINEAPPLE", "WATERMELLON", "AVOCADO", "COCONAT", "ROY", "BEVERAGE", "WHEAT" }));

        txtpricemeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpricemealActionPerformed(evt);
            }
        });

        btnsaveprice.setText("SAVE PRICE");
        btnsaveprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavepriceActionPerformed(evt);
            }
        });

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE");

        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        jButton5.setText("NEW ITEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbmealitem, 0, 210, Short.MAX_VALUE)
                            .addComponent(txtpricemeal)
                            .addComponent(txtdiscountmeals)
                            .addComponent(txtnewmeal)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnsaveprice)
                        .addGap(29, 29, 29)
                        .addComponent(btnupdate)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(34, 34, 34)
                        .addComponent(btnsearch)
                        .addGap(32, 32, 32)
                        .addComponent(jButton5)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(cmbmealitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtpricemeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdiscountmeals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtnewmeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsaveprice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnmealback.setBackground(new java.awt.Color(255, 255, 255));
        btnmealback.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        btnmealback.setForeground(new java.awt.Color(0, 0, 153));
        btnmealback.setText("BACK");
        btnmealback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmealbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnmealback)
                .addGap(20, 20, 20))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmealback, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnmealbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmealbackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Admin().setVisible(true);
    }//GEN-LAST:event_btnmealbackActionPerformed

    private void btnsavepriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavepriceActionPerformed
        // TODO add your handling code here:
        try{
        String url = "jdbc:mysql://localhost:3306/hoteldb";
        String username = "root";
        String password = "";
        conn = DriverManager.getConnection(url,username,password);
        st = conn.createStatement();
        
        if("BEVERAGE".equals(cmbmealitem.getSelectedItem())){
        String sqlsaveprice = "INSERT INTO tblmeals (CATEGORY,TEA,COFFEE,COCOA)VALUES ('"+cmbmealitem.getSelectedItem()+"',"
                + "'"+txtpricemeal.getText()+"','"+txtdiscountmeals.getText()+"','"+txtnewmeal.getText()+"')";
        if(!"".equals(txtpricemeal.getText()) && !"".equals(txtdiscountmeals.getText()) ){
        st.execute(sqlsaveprice);
       JOptionPane.showMessageDialog(null, "NEW PRICE SAVED");
       txtpricemeal.setText("");
       txtdiscountmeals.setText("");
       cmbmealitem.setSelectedIndex(0);
       
        }else{
        JOptionPane.showMessageDialog(null, "FAILED CHECK PRICE ENTERED");
        }
        }else if ("WHEAT".equals(cmbmealitem.getSelectedItem())){
        String sqlsaveprice = "INSERT INTO tblmealbread (CATEGORY,BREAD,MAFFIN,SCONS)VALUES ('"+cmbmealitem.getSelectedItem()+"',"
                + "'"+txtpricemeal.getText()+"','"+txtdiscountmeals.getText()+"','"+txtnewmeal.getText()+"')";
        if(!"".equals(txtpricemeal.getText()) && !"".equals(txtdiscountmeals.getText()) ){
        st.execute(sqlsaveprice);
       JOptionPane.showMessageDialog(null, "NEW PRICE SAVED");
       txtpricemeal.setText("");
       txtdiscountmeals.setText("");
       cmbmealitem.setSelectedIndex(0);
       
        }else{
        JOptionPane.showMessageDialog(null, "FAILED CHECK PRICE ENTERED");
        }
        }
        }catch(HeadlessException | SQLException ex){
        JOptionPane.showMessageDialog(null, "ERROR" + ex);
        }
    }//GEN-LAST:event_btnsavepriceActionPerformed

    private void txtpricemealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpricemealActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtpricemealActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
       try{
        conn = DriverManager.getConnection(url,username,password);
        st = conn.createStatement();
        String sqlupdate = "UPDATE tblmeals set TEA = '"+txtpricemeal.getText()+"',COFFEE= '"+txtdiscountmeals.getText()+"' ,COCOA = '"+txtnewmeal.getText()+"'   WHERE CATEGORY = ?";
        pst = conn.prepareStatement(sqlupdate);
        pst.setString(1, (String) cmbmealitem.getSelectedItem());
        pst.executeUpdate();
        String updateditem = (String) cmbmealitem.getSelectedItem();
        JOptionPane.showMessageDialog(null, "PRICE UPDATED FOR : " + updateditem);
       }catch(Exception ex){
       
       JOptionPane.showMessageDialog(null , ex);
       }
        
        
        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        
        try{
            
            conn = DriverManager.getConnection(url,username,password);
            st = conn.createStatement();
            String sqlsearch = "SELECT * FROM tblmeals WHERE CATEGORY = ?";
            pst = conn.prepareStatement(sqlsearch);
            pst.setString(1, (String) cmbmealitem.getSelectedItem());
            rs = pst.executeQuery();
            if(rs.next()){
            JOptionPane.showMessageDialog(null,"REQUISTING....");
            String item = rs.getString("CATEGORY");
            cmbmealitem.setSelectedItem(item);
            String price = rs.getString("TEA");
            txtpricemeal.setText(price);
            String discount = rs.getString("COFFEE");
            txtdiscountmeals.setText(discount);
            String cc = rs.getString("COCOA");
            txtnewmeal.setText(cc);
            }else{
            JOptionPane.showMessageDialog(null,"ITEM NOT FOUND");
            }
            
        
        
        }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
                }
    }//GEN-LAST:event_btnsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Meals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmealback;
    private javax.swing.JButton btnsaveprice;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cmbmealitem;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtdiscountmeals;
    private javax.swing.JTextField txtnewmeal;
    private javax.swing.JTextField txtpricemeal;
    // End of variables declaration//GEN-END:variables
}
