/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author owner
 */
public class Mealpricing extends javax.swing.JFrame {

    /**
     * Creates new form Mealpricing
     */
    
    
      
    Connection conn;
    Statement st;
    ResultSet rs;
    PreparedStatement pst;
    
    String url = "jdbc:mysql://localhost:3306/hoteldb";
    String username = "root";
    String password = "";
    
    
    public Mealpricing() {
        initComponents();
        hidepanels();
        showdate();
        loadicon();
    }
    
    void hidepanels(){
    jpbevarage.setVisible(false);
    jpmainmeals.setVisible(false);
    jpsnacks.setVisible(false);
    jpfruits.setVisible(false);
    
    }
    void showdate(){
    Date d = new Date();
    SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyy");
    lbdate.setText("Date : "+ s.format(d));
    
    }
     void loadicon(){
    ImageIcon icon = new ImageIcon();
    icon = new ImageIcon("Images/logo.png");
    setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbdate = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmbcategory = new javax.swing.JComboBox<>();
        jpbevarage = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txttea = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcoffee = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcocoa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtblacktea = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtchocolate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtmilk = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jpmainmeals = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtugali = new javax.swing.JTextField();
        txtrice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtpotatoes = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtcookedbananas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtpitza = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtsheders = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtchips = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtfish = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtbeeffry = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtbeefchoma = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtpock = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtchicken = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtcabbage = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtkales = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jpsnacks = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtbread = new javax.swing.JTextField();
        txtmaffin = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtscons = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtqueencake = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtpancake = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txttost = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtcookies = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtchapo = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtmariandazi = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtdonats = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jpfruits = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtmango = new javax.swing.JTextField();
        txtorange = new javax.swing.JTextField();
        txtbanana = new javax.swing.JTextField();
        txtpineapple = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtwatermellon = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtavocado = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtcoconut = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtroy = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 103, 5));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel1.setText("LUZURY  HOTEL PRICING ");

        lbdate.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        lbdate.setForeground(new java.awt.Color(255, 255, 255));
        lbdate.setText("DATE :");

        jPanel2.setBackground(new java.awt.Color(240, 145, 77));
        jPanel2.setLayout(null);

        cmbcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BEVARAGE", "MAINMEAL", "FRUITS", "SNACKS" }));
        cmbcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcategoryActionPerformed(evt);
            }
        });
        jPanel2.add(cmbcategory);
        cmbcategory.setBounds(390, 11, 212, 30);

        jpbevarage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("TEA  :");

        jLabel4.setText("COFFEE");

        jLabel5.setText("COCOA");

        jLabel6.setText("BLACK TEA");

        jLabel7.setText("CHOCOLATE");

        jLabel8.setText("MILK");

        jLabel44.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 51, 204));
        jLabel44.setText("LUXURY   HOTEL   BEVARAGE PRICING ");

        javax.swing.GroupLayout jpbevarageLayout = new javax.swing.GroupLayout(jpbevarage);
        jpbevarage.setLayout(jpbevarageLayout);
        jpbevarageLayout.setHorizontalGroup(
            jpbevarageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpbevarageLayout.createSequentialGroup()
                .addGroup(jpbevarageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpbevarageLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jpbevarageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(jpbevarageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttea)
                            .addComponent(txtcoffee)
                            .addComponent(txtcocoa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)
                        .addGroup(jpbevarageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(74, 74, 74)
                        .addGroup(jpbevarageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtblacktea)
                            .addComponent(txtchocolate)
                            .addComponent(txtmilk, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpbevarageLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel44)))
                .addContainerGap(359, Short.MAX_VALUE))
        );
        jpbevarageLayout.setVerticalGroup(
            jpbevarageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpbevarageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jpbevarageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtblacktea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jpbevarageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtchocolate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jpbevarageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcocoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtmilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel2.add(jpbevarage);
        jpbevarage.setBounds(0, 130, 1023, 200);

        jpmainmeals.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("UGALI");

        jLabel10.setText("RICE");

        jLabel11.setText("POTATOES");

        jLabel12.setText("COOKED BANANAS");

        jLabel13.setText("PITZA");

        jLabel14.setText("SHEDERS");

        jLabel15.setText("CHIPS");

        jLabel16.setText("FISH");

        jLabel17.setText("BEEF FRY");

        jLabel18.setText("BEEF CHOMA");

        jLabel19.setText("POCK");

        jLabel20.setText("CHICKEN");

        jLabel21.setText("CABBAGE");

        jLabel22.setText("KALES");

        jLabel43.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 51, 204));
        jLabel43.setText("LUXURY   HOTEL MAINMEAL PRICING");

        javax.swing.GroupLayout jpmainmealsLayout = new javax.swing.GroupLayout(jpmainmeals);
        jpmainmeals.setLayout(jpmainmealsLayout);
        jpmainmealsLayout.setHorizontalGroup(
            jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmainmealsLayout.createSequentialGroup()
                .addGroup(jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpmainmealsLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtrice, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpmainmealsLayout.createSequentialGroup()
                                    .addGroup(jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11))
                                    .addGroup(jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpmainmealsLayout.createSequentialGroup()
                                            .addGap(57, 57, 57)
                                            .addComponent(txtpotatoes, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpmainmealsLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtugali, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jpmainmealsLayout.createSequentialGroup()
                                .addGroup(jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcookedbananas)
                                    .addComponent(txtpitza, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(112, 112, 112)
                        .addGroup(jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpmainmealsLayout.createSequentialGroup()
                                .addGroup(jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(46, 46, 46)
                                .addGroup(jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtchips)
                                    .addComponent(txtsheders)
                                    .addComponent(txtfish)
                                    .addComponent(txtbeeffry, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpmainmealsLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtbeefchoma, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(170, 170, 170)
                        .addGroup(jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(56, 56, 56)
                        .addGroup(jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtpock)
                            .addComponent(txtchicken)
                            .addComponent(txtcabbage)
                            .addComponent(txtkales, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpmainmealsLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel43)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jpmainmealsLayout.setVerticalGroup(
            jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmainmealsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43)
                .addGap(41, 41, 41)
                .addGroup(jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtugali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtsheders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtpock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtchips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtchicken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtpotatoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtfish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtcabbage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtcookedbananas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtbeeffry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtkales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpmainmealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtbeefchoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpitza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(25, 25, 25))
        );

        jPanel2.add(jpmainmeals);
        jpmainmeals.setBounds(0, 100, 1020, 250);

        jpsnacks.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setText("BREAD  :");

        jLabel24.setText("MAFFIN");

        jLabel25.setText("SCONS");

        jLabel26.setText("QUEEN CAKE");

        jLabel27.setText("PAN CAKE");

        jLabel28.setText("TOST");

        jLabel29.setText("COOKIES");

        jLabel30.setText("CHAPO");

        jLabel31.setText("MARIANDAZI");

        jLabel32.setText("DONATS");

        jLabel42.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 51, 204));
        jLabel42.setText("LUXURY     HOTEL  SNACKS  PRICING");

        javax.swing.GroupLayout jpsnacksLayout = new javax.swing.GroupLayout(jpsnacks);
        jpsnacks.setLayout(jpsnacksLayout);
        jpsnacksLayout.setHorizontalGroup(
            jpsnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpsnacksLayout.createSequentialGroup()
                .addGroup(jpsnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpsnacksLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jpsnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(45, 45, 45)
                        .addGroup(jpsnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtbread)
                            .addComponent(txtmaffin)
                            .addComponent(txtscons)
                            .addComponent(txtqueencake, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(91, 91, 91)
                        .addGroup(jpsnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(74, 74, 74)
                        .addGroup(jpsnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtcookies, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpancake, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttost, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtchapo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(100, 100, 100)
                        .addGroup(jpsnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addGap(70, 70, 70)
                        .addGroup(jpsnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmariandazi)
                            .addComponent(txtdonats, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(jpsnacksLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel42)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jpsnacksLayout.setVerticalGroup(
            jpsnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpsnacksLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addGap(18, 18, 18)
                .addGroup(jpsnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtbread, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtpancake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(txtmariandazi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jpsnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmaffin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(txttost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(txtdonats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jpsnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtscons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(txtcookies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jpsnacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtqueencake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(txtchapo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel2.add(jpsnacks);
        jpsnacks.setBounds(0, 70, 1020, 240);

        jpfruits.setBackground(new java.awt.Color(255, 255, 255));

        jLabel33.setText("MANGO");

        jLabel34.setText("ORANGE");

        jLabel35.setText("BANANA");

        jLabel36.setText("PINEAPPLE");

        txtbanana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbananaActionPerformed(evt);
            }
        });

        jLabel37.setText("WATERMELLON");

        jLabel38.setText("AVOCADO");

        jLabel39.setText("COCONUT");

        jLabel40.setText("ROY");

        txtroy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtroyActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 51, 255));
        jLabel41.setText("LUXURY   HOTEL FRUITS   ");

        javax.swing.GroupLayout jpfruitsLayout = new javax.swing.GroupLayout(jpfruits);
        jpfruits.setLayout(jpfruitsLayout);
        jpfruitsLayout.setHorizontalGroup(
            jpfruitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfruitsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpfruitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addGap(50, 50, 50)
                .addGroup(jpfruitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtmango)
                    .addComponent(txtorange)
                    .addComponent(txtbanana)
                    .addComponent(txtpineapple, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addGap(169, 169, 169)
                .addGroup(jpfruitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40))
                .addGap(77, 77, 77)
                .addGroup(jpfruitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtwatermellon)
                    .addComponent(txtavocado)
                    .addComponent(txtcoconut)
                    .addComponent(txtroy, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpfruitsLayout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addComponent(jLabel41)
                .addGap(332, 332, 332))
        );
        jpfruitsLayout.setVerticalGroup(
            jpfruitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpfruitsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jpfruitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtmango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(txtwatermellon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jpfruitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtorange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(txtavocado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jpfruitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtbanana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(txtcoconut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jpfruitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txtpineapple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(txtroy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel2.add(jpfruits);
        jpfruits.setBounds(0, 50, 1020, 250);

        btnsave.setBackground(new java.awt.Color(255, 255, 255));
        btnsave.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        btnsave.setForeground(new java.awt.Color(0, 204, 51));
        btnsave.setText("SAVE PRICE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(255, 255, 255));
        btnupdate.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(51, 103, 255));
        btnupdate.setText("UPDATE PRICE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(255, 255, 255));
        btndelete.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 0, 0));
        btndelete.setText("DELETE  PRICE");

        btnsearch.setBackground(new java.awt.Color(255, 153, 153));
        btnsearch.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        btnsearch.setText("SEARCH ITEMS");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(255, 255, 255));
        btnback.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        btnback.setForeground(new java.awt.Color(0, 51, 255));
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(lbdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnsave)
                .addGap(66, 66, 66)
                .addComponent(btnupdate)
                .addGap(54, 54, 54)
                .addComponent(btndelete)
                .addGap(59, 59, 59)
                .addComponent(btnsearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnsave, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcategoryActionPerformed
        // TODO add your handling code here:
        if("BEVARAGE".equals(cmbcategory.getSelectedItem())){
        jpbevarage.setVisible(true);
        jpsnacks.setVisible(false);
        jpmainmeals.setVisible(false);
        jpfruits.setVisible(false);
        
        
            txttea.setText("");
            txtcoffee.setText("");
            txtcocoa.setText("");
            txtblacktea.setText("");
            txtchocolate.setText("");
            txtmilk.setText(""); 
        
        }else if("MAINMEAL".equals(cmbcategory.getSelectedItem())){
        jpmainmeals.setVisible(true);
        jpbevarage.setVisible(false);
        jpsnacks.setVisible(false);
        jpfruits.setVisible(false);
        
        
            txtugali.setText("");
            txtrice.setText("");
            txtpotatoes.setText("");
            txtcookedbananas.setText("");
            txtpitza.setText("");
            txtchips.setText("");
            txtfish.setText("");
            txtsheders.setText("");
            txtbeeffry.setText("");
            txtbeefchoma.setText("");
            txtpock.setText("");
            txtchicken.setText("");
            txtcabbage.setText("");
            txtkales.setText("");
        
    
        }else if ("SNACKS".equals(cmbcategory.getSelectedItem())){
        jpmainmeals.setVisible(false);
        jpbevarage.setVisible(false);
        jpsnacks.setVisible(true);
        jpfruits.setVisible(false);
        
        
            txtbread.setText("");
            txtmaffin.setText("");
            txtscons.setText("");
            txtqueencake.setText("");
            txtpancake.setText("");
            txttost.setText("");
            txtcookies.setText("");
            txtchapo.setText("");
            txtmariandazi.setText("");
            txtdonats.setText("");
        
        }else if ("FRUITS".equals(cmbcategory.getSelectedItem())){
        jpbevarage.setVisible(false);
    jpmainmeals.setVisible(false);
    jpsnacks.setVisible(false);
    jpfruits.setVisible(true);
    
            txtmango.setText("");
            txtorange.setText("");
            txtbanana.setText("");
            txtpineapple.setText("");
            txtwatermellon.setText("");
            txtavocado.setText("");
            txtcoconut.setText("");
            txtroy.setText("");
        }
    }//GEN-LAST:event_cmbcategoryActionPerformed

    private void txtbananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbananaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbananaActionPerformed

    private void txtroyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtroyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtroyActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        this .dispose();
        new Admin().setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        
        
        try{
       
        conn = DriverManager.getConnection(url,username,password);
        st = conn.createStatement();
        
        if("BEVARAGE".equals(cmbcategory.getSelectedItem())){
        String sqlsaveprice = "INSERT INTO tblbevarage (CATEGORY,TEA,COFFEE,COCOA,BLACKTEA,CHOCOLATE,MILK)VALUES ('"+cmbcategory.getSelectedItem()+"',"
                + "'"+txttea.getText()+"','"+txtcoffee.getText()+"','"+txtcocoa.getText()+"','"+txtblacktea.getText()+"','"+txtchocolate.getText()+"','"+txtmilk.getText()+"')";
        if(!"".equals(txttea.getText()) && !"".equals(txtcoffee.getText()) ){
        st.execute(sqlsaveprice);
       JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 12px;\">NEW PRICE SAVED</i></HTML>");
       
       
        }else{
        JOptionPane.showMessageDialog(null, "FAILED CHECK PRICE ENTERED");
        }
        }else if ("SNACKS".equals(cmbcategory.getSelectedItem())){
        String sqlsaveprice = "INSERT INTO tblsnacks(CATEGORY,BREAD,MAFFIN,SCONS,QUEENCAKE,PANCAKE,TOST,COOKIES,CHAPO,MARIANDAZI,DONATS)VALUES ('"+cmbcategory.getSelectedItem()+"',"
                + "'"+txtbread.getText()+"','"+txtmaffin.getText()+"','"+txtscons.getText()+"','"+txtqueencake.getText()+"','"+txtpancake.getText()+"'"
                + ",'"+txttost.getText()+"','"+txtcookies.getText()+"','"+txtchapo.getText()+"','"+txtmariandazi.getText()+"','"+txtdonats.getText()+"')";
        if(!"".equals(txtbread.getText()) && !"".equals(txtmaffin.getText()) ){
        st.execute(sqlsaveprice);
       JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 12px;\">NEW PRICE SAVED</i></HTML>");
       
       
        }else{
        JOptionPane.showMessageDialog(null, "FAILED CHECK PRICE ENTERED");
        }
        }else if("MAINMEAL".equals(cmbcategory.getSelectedItem())){
        
          String sqlsaveprice = "INSERT INTO tblmainmeals(CATEGORY,UGALI,RICE,POTATOES,BANANA,PITZA,SHEDERS,CHIPS,FISH,BEEFFRY,BEEFCHOMA,POCK,CHICKEN,CABBAGE,KALES)"
                  + "VALUES ('"+cmbcategory.getSelectedItem()+"',"
                + "'"+txtugali.getText()+"','"+txtrice.getText()+"','"+txtpotatoes.getText()+"','"+txtcookedbananas.getText()+"','"+txtpitza.getText()+"'"
                + ",'"+txtsheders.getText()+"','"+txtchips.getText()+"','"+txtfish.getText()+"','"+txtbeeffry.getText()+"','"+txtbeefchoma.getText()+"',"
                  + "'"+txtpock.getText()+"','"+txtchicken.getText()+"','"+txtcabbage.getText()+"','"+txtkales.getText()+"')";
        if(!"".equals(txtugali.getText()) && !"".equals(txtrice.getText()) ){
        st.execute(sqlsaveprice);
       JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 12px;\">NEW PRICE SAVED</i></HTML>");
       
       
        }else{
        JOptionPane.showMessageDialog(null, "FAILED CHECK PRICE ENTERED");
        }
        
        }else if("FRUITS".equals(cmbcategory.getSelectedItem())){
        
          String sqlsaveprice = "INSERT INTO tblfruits (CATEGORY,MANGO,ORANGE,BANANA,PINEAPPLE,WATERMELLON,AVOCADO,COCONUT,ROY)"
                  + "VALUES ('"+cmbcategory.getSelectedItem()+"',"
                + "'"+txtmango.getText()+"','"+txtorange.getText()+"','"+txtbanana.getText()+"','"+txtpineapple.getText()+"','"+txtwatermellon.getText()+"'"
                + ",'"+txtavocado.getText()+"','"+txtcoconut.getText()+"','"+txtroy.getText()+"')";
        if(!"".equals(txtmango.getText()) && !"".equals(txtorange.getText()) ){
        st.execute(sqlsaveprice);
       JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 12px;\">NEW PRICE SAVED</i></HTML>");
       
       
        }else{
        JOptionPane.showMessageDialog(null, "FAILED CHECK PRICE ENTERED");
        }
            
        }else {
        
        //JOptionPane.showMessageDialog(null, "CATEGORY ALREADY EXIST" );
        }
        }catch(HeadlessException ex){
        JOptionPane.showMessageDialog(null, "ERROR" + ex);
        }catch(SQLException ncie){
        JOptionPane.showMessageDialog(null,  "ERROR" + ncie );
        }
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        
        try{
        
             conn = DriverManager.getConnection(url,username,password);
        st= conn.createStatement();
        if("BEVARAGE".equals(cmbcategory.getSelectedItem())){
            //update bevarage
        String sqlupdate = "UPDATE tblbevarage set TEA ='"+txttea.getText()+"',COFFEE ='"+txtcoffee.getText()+"',COCOA='"+txtcocoa.getText()+"',"
                + "BLACKTEA='"+txtblacktea.getText()+"',CHOCOLATE='"+txtchocolate.getText()+"',MILK='"+txtmilk.getText()+"' WHERE CATEGORY = ?";
        pst=conn.prepareStatement(sqlupdate);
        pst.setString(1,(String)cmbcategory.getSelectedItem() );
        
         pst.executeUpdate();
        
        String updatedgroung = (String) cmbcategory.getSelectedItem();
        JOptionPane.showMessageDialog(null," "+updatedgroung+"  "+"PRICES UPDATED");
        }else if ("SNACKS".equals(cmbcategory.getSelectedItem())){
        // update snacks
        
        String sqlupdate = "UPDATE tblsnacks SET BREAD='"+txtbread.getText()+"',MAFFIN='"+txtmaffin.getText()+"',SCONS='"+txtscons.getText()+"',"
                + "QUEENCAKE='"+txtqueencake.getText()+"',PANCAKE='"+txtpancake.getText()+"',TOST='"+txttost.getText()+"',COOKIES='"+txtcookies.getText()+"',"
                + "CHAPO='"+txtchapo.getText()+"',MARIANDAZI='"+txtmariandazi.getText()+"',DONATS='"+txtdonats.getText()+"' WHERE CATEGORY = ?";
        pst=conn.prepareStatement(sqlupdate);
        pst.setString(1,(String)cmbcategory.getSelectedItem() );
        
         pst.executeUpdate();
         
         String updatedgroung = (String) cmbcategory.getSelectedItem();
        JOptionPane.showMessageDialog(null," "+updatedgroung+"  "+"PRICES UPDATED");
        
        } else if("MAINMEAL".equals(cmbcategory.getSelectedItem())){
            //update mainmeals
            String sqlupdate = "UPDATE tblmainmeals SET UGALI='"+txtugali.getText()+"',RICE='"+txtrice.getText()+"',POTATOES='"+txtpotatoes.getText()+"',"
                    + "BANANA='"+txtcookedbananas.getText()+"',PITZA='"+txtpitza.getText()+"',SHEDERS='"+txtsheders.getText()+"',CHIPS='"+txtchips.getText()+"',"
                    + "FISH='"+txtfish.getText()+"',BEEFFRY='"+txtbeeffry.getText()+"',BEEFCHOMA='"+txtbeefchoma.getText()+"',POCK='"+txtpock.getText()+"',"
                    + "CHICKEN='"+txtchicken.getText()+"',CABBAGE='"+txtcabbage.getText()+"',KALES='"+txtkales.getText()+"' WHERE CATEGORY = ?";
        pst=conn.prepareStatement(sqlupdate);
        pst.setString(1,(String)cmbcategory.getSelectedItem() );
        
         pst.executeUpdate();
         
         String updatedgroung = (String) cmbcategory.getSelectedItem();
        JOptionPane.showMessageDialog(null," "+updatedgroung+"  "+"PRICES UPDATED");
        
        }else if("FRUITS".equals(cmbcategory.getSelectedItem())){
            //update fruits
            
            String sqlupdate = "UPDATE tblfruits SET MANGO='"+txtmango.getText()+"',ORANGE='"+txtorange.getText()+"',BANANA='"+txtbanana.getText()+"',"
                    + "PINEAPPLE='"+txtpineapple.getText()+"',"
                    + "WATERMELLON='"+txtwatermellon.getText()+"',AVOCADO='"+txtavocado.getText()+"',COCONUT='"+txtcoconut.getText()+"',ROY='"+txtroy.getText()+"' WHERE CATEGORY = ?";
        pst=conn.prepareStatement(sqlupdate);
        pst.setString(1,(String)cmbcategory.getSelectedItem() );
        
         pst.executeUpdate();
        
        String updatedgroung = (String) cmbcategory.getSelectedItem();
        JOptionPane.showMessageDialog(null," "+updatedgroung+"  "+"PRICES UPDATED");
            
            
        
        }
        }catch(HeadlessException  ex){
        
        JOptionPane.showMessageDialog(null, "ERROR" + ex);
        }catch(SQLException sqlex){
        JOptionPane.showMessageDialog(null, "ERROR" + sqlex);
        }
        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        
        try{
            
            conn = DriverManager.getConnection(url,username,password);
            st = conn.createStatement();
            
            if("BEVARAGE".equals(cmbcategory.getSelectedItem())){
            String sqlsearch = "SELECT * FROM tblbevarage WHERE CATEGORY = ?";
            pst = conn.prepareStatement(sqlsearch);
            pst.setString(1, (String) cmbcategory.getSelectedItem());
            rs = pst.executeQuery();
            if(rs.next()){
            JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 12px;\">REQUISTING....</i></HTML>");
            String item = rs.getString("CATEGORY");
            cmbcategory.setSelectedItem(item);
            txttea.setText(rs.getString("TEA"));
            txtcoffee.setText(rs.getString("COFFEE"));
            txtcocoa.setText(rs.getString("COCOA"));
            txtblacktea.setText(rs.getString("BLACKTEA"));
            txtchocolate.setText(rs.getString("CHOCOLATE"));
            txtmilk.setText(rs.getString("MILK"));
            }
            
            
            else{
            JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: #FF6705; font-size: 12px;\">CATEGORY NOT FOUND !!!</i></HTML>");
            }
            }else if ("SNACKS".equals(cmbcategory.getSelectedItem())){
            String sqlsearch = "SELECT * FROM tblsnacks WHERE CATEGORY = ?";
            pst = conn.prepareStatement(sqlsearch);
            pst.setString(1, (String) cmbcategory.getSelectedItem());
            rs = pst.executeQuery();
            if(rs.next()){
            JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 12px;\">REQUISTING....</i></HTML>");
            String item = rs.getString("CATEGORY");
            cmbcategory.setSelectedItem(item);
            txtbread.setText(rs.getString("BREAD"));
            txtmaffin.setText(rs.getString("MAFFIN"));
            txtscons.setText(rs.getString("SCONS"));
            txtqueencake.setText(rs.getString("QUEENCAKE"));
            txtpancake.setText(rs.getString("PANCAKE"));
            txttost.setText(rs.getString("TOST"));
            txtcookies.setText(rs.getString("COOKIES"));
            txtchapo.setText(rs.getString("CHAPO"));
            txtmariandazi.setText(rs.getString("MARIANDAZI"));
            txtdonats.setText(rs.getString("DONATS"));
            }
            
            
            else{
            JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: #FF6705; font-size: 12px;\">CATEGORY NOT FOUND !!!</i></HTML>");
            }
            
            }else if ("FRUITS".equals(cmbcategory.getSelectedItem())){
            String sqlsearch = "SELECT * FROM tblfruits WHERE CATEGORY = ?";
            pst = conn.prepareStatement(sqlsearch);
            pst.setString(1, (String) cmbcategory.getSelectedItem());
            rs = pst.executeQuery();
            if(rs.next()){
            JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 12px;\">REQUISTING....</i></HTML>");
            String item = rs.getString("CATEGORY");
            cmbcategory.setSelectedItem(item);
            txtmango.setText(rs.getString("MANGO"));
            txtorange.setText(rs.getString("ORANGE"));
            txtbanana.setText(rs.getString("BANANA"));
            txtpineapple.setText(rs.getString("PINEAPPLE"));
            txtwatermellon.setText(rs.getString("WATERMELLON"));
            txtavocado.setText(rs.getString("AVOCADO"));
            txtcoconut.setText(rs.getString("COCONUT"));
            txtroy.setText(rs.getString("ROY"));
            
            }
            
            
            else{
            JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: #FF6705; font-size: 12px;\">CATEGORY NOT FOUND !!!</i></HTML>");
            }
            
            }else if ("MAINMEAL".equals(cmbcategory.getSelectedItem())){
            String sqlsearch = "SELECT * FROM tblmainmeals WHERE CATEGORY = ?";
            pst = conn.prepareStatement(sqlsearch);
            pst.setString(1, (String) cmbcategory.getSelectedItem());
            rs = pst.executeQuery();
            if(rs.next()){
           JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 12px;\">REQUISTING....</i></HTML>");
            String item = rs.getString("CATEGORY");
            cmbcategory.setSelectedItem(item);
            txtugali.setText(rs.getString("UGALI"));
            txtrice.setText(rs.getString("RICE"));
            txtpotatoes.setText(rs.getString("POTATOES"));
            txtcookedbananas.setText(rs.getString("BANANA"));
            txtpitza.setText(rs.getString("PITZA"));
            txtchips.setText(rs.getString("CHIPS"));
            txtfish.setText(rs.getString("FISH"));
            txtsheders.setText(rs.getString("SHEDERS"));
            txtbeeffry.setText(rs.getString("BEEFFRY"));
            txtbeefchoma.setText(rs.getString("BEEFCHOMA"));
            txtpock.setText(rs.getString("POCK"));
            txtchicken.setText(rs.getString("CHICKEN"));
            txtcabbage.setText(rs.getString("CABBAGE"));
            txtkales.setText(rs.getString("KALES"));
            
            }
            
            
            else{
            JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: #FF6705; font-size: 12px;\">CATEGORY NOT FOUND !!!</i></HTML>");
            }
            
            }else{
            JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: #FF6705; font-size: 12px;\">SELECT CATEGORY</i></HTML>");
            
            }
            
        
        
        }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
                }
        
        
    }//GEN-LAST:event_btnsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mealpricing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mealpricing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mealpricing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mealpricing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mealpricing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cmbcategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpbevarage;
    private javax.swing.JPanel jpfruits;
    private javax.swing.JPanel jpmainmeals;
    private javax.swing.JPanel jpsnacks;
    private javax.swing.JLabel lbdate;
    private javax.swing.JTextField txtavocado;
    private javax.swing.JTextField txtbanana;
    private javax.swing.JTextField txtbeefchoma;
    private javax.swing.JTextField txtbeeffry;
    private javax.swing.JTextField txtblacktea;
    private javax.swing.JTextField txtbread;
    private javax.swing.JTextField txtcabbage;
    private javax.swing.JTextField txtchapo;
    private javax.swing.JTextField txtchicken;
    private javax.swing.JTextField txtchips;
    private javax.swing.JTextField txtchocolate;
    private javax.swing.JTextField txtcocoa;
    private javax.swing.JTextField txtcoconut;
    private javax.swing.JTextField txtcoffee;
    private javax.swing.JTextField txtcookedbananas;
    private javax.swing.JTextField txtcookies;
    private javax.swing.JTextField txtdonats;
    private javax.swing.JTextField txtfish;
    private javax.swing.JTextField txtkales;
    private javax.swing.JTextField txtmaffin;
    private javax.swing.JTextField txtmango;
    private javax.swing.JTextField txtmariandazi;
    private javax.swing.JTextField txtmilk;
    private javax.swing.JTextField txtorange;
    private javax.swing.JTextField txtpancake;
    private javax.swing.JTextField txtpineapple;
    private javax.swing.JTextField txtpitza;
    private javax.swing.JTextField txtpock;
    private javax.swing.JTextField txtpotatoes;
    private javax.swing.JTextField txtqueencake;
    private javax.swing.JTextField txtrice;
    private javax.swing.JTextField txtroy;
    private javax.swing.JTextField txtscons;
    private javax.swing.JTextField txtsheders;
    private javax.swing.JTextField txttea;
    private javax.swing.JTextField txttost;
    private javax.swing.JTextField txtugali;
    private javax.swing.JTextField txtwatermellon;
    // End of variables declaration//GEN-END:variables
}
