/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

/**
 *
 * @author owner
 */
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
public class Weddingcontrol extends javax.swing.JFrame {

    /**
     * Creates new form Weddingcontrol
     */
    java.sql.Date sqldate;
    
     Connection conn;
    Statement st;
    ResultSet rs;
    PreparedStatement pst;
    
    String url = "jdbc:mysql://localhost:3306/hoteldb";
    String username = "root";
    String password = "";
    
    public Weddingcontrol() {
        initComponents();
        loadicon();
        disableinput();
    }
    void loadicon(){
    ImageIcon icon = new ImageIcon();
    icon = new ImageIcon("Images/logo.png");
    setIconImage(icon.getImage());
    }
    void disableinput(){
    btnsave.setEnabled(false);
    btnprint.setEnabled(false);
    btnrates.setEnabled(false);
    txtprice.setEditable(false);
    txtdiscount.setEditable(false);
    txtnetprice.setEditable(false);
    txtid.setEnabled(false);
    txtphone.setEnabled(false);
    txtemail.setEnabled(false);
    jdwedding.setEnabled(false);
    cmbground.setEnabled(false);
    cmbmealclass.setEnabled(false);
    cmbconvoy.setEnabled(false);
    txtattendance.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnapprovebook = new javax.swing.JButton();
        btnreports = new javax.swing.JButton();
        btncancelbook = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbground = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jdwedding = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtattendance = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbmealclass = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbconvoy = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdiscount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtnetprice = new javax.swing.JTextField();
        btnrates = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jpreceipt = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lbdate = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tareceipt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LUXURY HOTEL WEDDING CONTROL");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 92, 12));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel1.setText("WEDDING  GROUND  ALLOCATION ");

        btnlogout.setBackground(new java.awt.Color(255, 255, 255));
        btnlogout.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 0, 0));
        btnlogout.setText("LOGOUT");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(240, 162, 55));

        jPanel3.setBackground(new java.awt.Color(240, 92, 12));

        jLabel2.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ACTION  MENU");

        btnapprovebook.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        btnapprovebook.setText("APPROVE BOOK");
        btnapprovebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapprovebookActionPerformed(evt);
            }
        });

        btnreports.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        btnreports.setText("REPORTS");
        btnreports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportsActionPerformed(evt);
            }
        });

        btncancelbook.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        btncancelbook.setText("CANCEL BOOK");

        jButton6.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        jButton6.setText("CONFERENCES");

        jButton7.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        jButton7.setText("TRAINING");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnapprovebook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnreports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncancelbook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnapprovebook, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnreports, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncancelbook, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("WEDDING GROUND");

        cmbground.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAIROBI", "KISUMU", "ELDORET", "MOMBASA" }));

        jLabel4.setText("WEDDING DAY");

        jdwedding.setDateFormatString("dd-MM-yyyy");

        jLabel5.setText("NO OF ATTENDANCE");

        jLabel6.setText("MEALS CLASS");

        cmbmealclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLASS A", "CLASS B", "NA" }));

        jLabel7.setText("WEDDING CONVOY");

        cmbconvoy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HOTEL CONVOY", "PRESIDENTIAL CONVOY", "NA" }));

        jLabel8.setText("NET PRICE");

        jLabel9.setText("DISCOUNT");

        jLabel10.setText("NET PAY");

        btnrates.setBackground(new java.awt.Color(255, 255, 255));
        btnrates.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        btnrates.setForeground(new java.awt.Color(0, 204, 51));
        btnrates.setText("CHECK RATES");
        btnrates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnratesActionPerformed(evt);
            }
        });

        jLabel11.setText("CLIENT ID No.");

        jLabel12.setText("CLIENT PHONE");

        jLabel13.setText("CLIENT EMAIL");

        btnadd.setText("ADD RESERVATION");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnsave.setText("SAVE RESERVATION");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnprint.setText("PRINT TICKET");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("WEDDING TICKET ");

        jpreceipt.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setText("LUXURY HOTEL WEDDING TICKET");

        lbdate.setText("DATE OF ISSUE");

        jLabel17.setText("PO BOX 0001-3006  ELDORET");

        jLabel18.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        jLabel18.setText("THANK YOU HAPPY WEDDING");

        tareceipt.setColumns(20);
        tareceipt.setRows(5);
        jScrollPane2.setViewportView(tareceipt);

        javax.swing.GroupLayout jpreceiptLayout = new javax.swing.GroupLayout(jpreceipt);
        jpreceipt.setLayout(jpreceiptLayout);
        jpreceiptLayout.setHorizontalGroup(
            jpreceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpreceiptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpreceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(lbdate)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addContainerGap(88, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jpreceiptLayout.setVerticalGroup(
            jpreceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpreceiptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbground, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdwedding, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(txtattendance)
                                    .addComponent(cmbmealclass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbconvoy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtprice)
                                    .addComponent(txtdiscount)
                                    .addComponent(txtnetprice)
                                    .addComponent(txtid)
                                    .addComponent(txtphone)
                                    .addComponent(txtemail)))
                            .addComponent(btnrates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel14))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jpreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnadd)
                        .addGap(18, 18, 18)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnprint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jdwedding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtattendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbmealclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(cmbconvoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(txtdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtnetprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnrates, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsave, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnprint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(btnlogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnreportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreportsActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnapprovebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapprovebookActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Approvebookingevents().setVisible(true);
    }//GEN-LAST:event_btnapprovebookActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        try{
            if(!"".equals(txtid.getText())&& !"".equals(txtphone.getText())){
        String ground = (String)cmbground.getSelectedItem();
        Date date = jdwedding.getDate();
        sqldate = new java.sql.Date( date.getTime());
       String mealclass = (String)cmbmealclass.getSelectedItem();
       String convoy = (String)cmbconvoy.getSelectedItem();
        String price = txtprice.getText();
        String discount = txtdiscount.getText();
        String netprice = txtnetprice.getText();
        String idnumber = txtid.getText();
        String email = txtemail.getText();
        String phone = txtphone.getText();
        String attendance = txtattendance.getText();
        String status = "ALLOCATED GROUND";
        
        String receipt = "GROUND         :"+"  " + ground +"\n"+ "ATTENDANCE:"+"  " + attendance +"\n"+ "BOOK DATE    :"+"  "+ sqldate +"\n" +"MEAL CLASS  :" +"  "
                +mealclass+ "\n" +"CONVOY          :"+"  " + convoy+"\n" + "ID NUMBER    : " +idnumber+"\n" + "PHONE            :"+"  " +phone+"\n" +
                "EMAIL               :" +"  "+email+ "\n" +"\n" +"TOTAL PRICE :"+"  Ksh    "+price+"\n" + "DISCOUNT      :"+"  Ksh    "+discount+"\n" + "NET   PAY         :"+"  Ksh    "+netprice ;
            
        tareceipt.setText(""+receipt);
        btnprint.setEnabled(true);
        
        
        conn = DriverManager.getConnection(url,username,password);
        st = conn.createStatement();
        String sqlsave = "INSERT INTO tblwedding(IDNUMBER,GROUND,WEDDINGDATE,ATTENDANCE,MEALCLASS,CONVOY,TOTALCOST,DISCOUNT,NETPRICE,PHONE,EMAIL,STATUS)"
                + " VALUES ('"+idnumber+"','"+ground+"','"+sqldate+"','"+attendance+"','"+mealclass+"','"+convoy+"','"+price+"',"
                + "'"+discount+"','"+netprice+"','"+phone+"','"+email+"','"+status+"') ";
        st.execute(sqlsave);
        JOptionPane.showMessageDialog(null,"<HTML><b style=\"color: green; font-size: 16px;\">GROUND ALLOCATED SUCCESSFULLY </b></HTML>");
            }else {
            JOptionPane.showMessageDialog(null,"<HTML><b style=\"color: #F05C0C; font-size: 16px;\">Enter All Data!!!</b></HTML>");
            
            }
        
        
        }catch(NumberFormatException ex){
        
        JOptionPane.showMessageDialog(null,"<HTML><b style=\"color: #F05C0C; font-size: 16px;\">CHECK NUMBERS ENTERED</b></HTML>");
        }catch (NullPointerException npe){
        JOptionPane.showMessageDialog(null,"<HTML><b style=\"color: #F05C0C; font-size: 16px;\">Enter Dates!!!</b></HTML>");
        } catch (SQLException sql) {
            Logger.getLogger(Weddingcontrol.class.getName()).log(Level.SEVERE, null, sql);
            JOptionPane.showMessageDialog(null, sql);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnratesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnratesActionPerformed
        // TODO add your handling code here:
        
        try{
         conn = DriverManager.getConnection(url,username,password);
         st = conn.createStatement();
         String sqlsearch = "SELECT * FROM tblweddingpricing  WHERE GROUD = ?";
         pst = conn.prepareStatement(sqlsearch);
         pst.setString(1,(String) cmbground.getSelectedItem());
         rs=pst.executeQuery();
         if(rs.next()){
          JOptionPane.showMessageDialog(null,"<HTML><b style=\"color: green; font-size: 16px;\">Processing requist ...</b></HTML>");
          btnsave.setEnabled(true);
          txtid.setEnabled(true);
    txtphone.setEnabled(true);
    txtemail.setEnabled(true);
         String ground = rs.getString("GROUD");
         cmbground.setSelectedItem(ground);
       String mealclassA = rs.getString("MEALCLASSA");
       String mealclassB = rs.getString("MEALCLASSB");
        String convoyP = rs.getString("PRESIDENTIALCONVOY");
        String convoyH = rs.getString("HOTELCONVOY");
        String price = rs.getString("NETPRICE");
        String discount = rs.getString("DISCOUNT");
        
         int mealclass = cmbmealclass.getSelectedIndex();
         int convoy = cmbconvoy.getSelectedIndex();
         String att = txtattendance.getText();
         int attendance = Integer.parseInt(att);
         int p = Integer.parseInt(price);
         int d = Integer.parseInt(discount);
         int mealA = Integer.parseInt(mealclassA);
         int mealB = Integer.parseInt(mealclassB);
         int conP= Integer.parseInt(convoyP);
         int conH= Integer.parseInt(convoyH);
         if (mealclass == 0 && convoy == 0){
         double totalcost = (mealA * attendance) + conH + p;
         double totaldiscount = totalcost * (d*0.01);
         double netpay = totalcost - totaldiscount;
         txtprice.setText(""+totalcost);
         txtdiscount.setText(""+totaldiscount);
         txtnetprice.setText(""+netpay);
         }else if (mealclass == 0 && convoy == 1){
         double totalcost = (mealA * attendance) + conP + p;
         double totaldiscount = totalcost * (d*0.01);
         double netpay = totalcost - totaldiscount;
         txtprice.setText(""+totalcost);
         txtdiscount.setText(""+totaldiscount);
         txtnetprice.setText(""+netpay);
         } else if(mealclass == 0 && convoy == 2){
         double totalcost = (mealA * attendance) + 0 + p;
         double totaldiscount = totalcost * (d*0.01);
         double netpay = totalcost - totaldiscount;
         txtprice.setText(""+totalcost);
         txtdiscount.setText(""+totaldiscount);
         txtnetprice.setText(""+netpay);
         }else if (mealclass == 1 && convoy == 0){
         double totalcost = (mealB * attendance) + conH + p;
         double totaldiscount = totalcost * (d*0.01);
         double netpay = totalcost - totaldiscount;
         txtprice.setText(""+totalcost);
         txtdiscount.setText(""+totaldiscount);
         txtnetprice.setText(""+netpay);
         }else if(mealclass == 1 && convoy == 1){
         double totalcost = (mealB * attendance) + conP + p;
         double totaldiscount = totalcost * (d*0.01);
         double netpay = totalcost - totaldiscount;
         txtprice.setText(""+totalcost);
         txtdiscount.setText(""+totaldiscount);
         txtnetprice.setText(""+netpay);
         }else if (mealclass == 1 && convoy == 2){
         double totalcost = (mealB * attendance) + 0 + p;
         double totaldiscount = totalcost * (d*0.01);
         double netpay = totalcost - totaldiscount;
         txtprice.setText(""+totalcost);
         txtdiscount.setText(""+totaldiscount);
         txtnetprice.setText(""+netpay);
         }else if (mealclass == 2 && convoy == 0){
         double totalcost = (0 * attendance) + conH + p;
         double totaldiscount = totalcost * (d*0.01);
         double netpay = totalcost - totaldiscount;
         txtprice.setText(""+totalcost);
         txtdiscount.setText(""+totaldiscount);
         txtnetprice.setText(""+netpay);
         }else if (mealclass == 2 && convoy == 1){
         double totalcost = (0 * attendance) + conP + p;
         double totaldiscount = totalcost * (d*0.01);
         double netpay = totalcost - totaldiscount;
         txtprice.setText(""+totalcost);
         txtdiscount.setText(""+totaldiscount);
         txtnetprice.setText(""+netpay);
         }else if (mealclass == 2 && convoy == 2){
         double totalcost = (0 * attendance) + 0 + p;
         double totaldiscount = totalcost * (d*0.01);
         double netpay = totalcost - totaldiscount;
         txtprice.setText(""+totalcost);
         txtdiscount.setText(""+totaldiscount);
         txtnetprice.setText(""+netpay);
         
         
        
         
         } 
         
         
         
         }else {
         JOptionPane.showMessageDialog(null,"<HTML><b style=\"color: #F05C0C; font-size: 16px;\">GROUND NOT AVAILABLE!!!</b></HTML>");
         
         }
        
        
        }catch(HeadlessException | SQLException ex){
        JOptionPane.showMessageDialog(null, ex);
        } catch(NumberFormatException nfe){
           JOptionPane.showMessageDialog(null,"<HTML><b style=\"color: #F05C0C; font-size: 16px;\">CHECK ATTENDANCE NUMBER ?</b></HTML>"); 
        }
        
    }//GEN-LAST:event_btnratesActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        
        btnsave.setEnabled(false);
    btnprint.setEnabled(false);
    btnrates.setEnabled(true);
    txtprice.setEnabled(false);
    txtdiscount.setEnabled(false);
    txtnetprice.setEnabled(false);
    
    jdwedding.setEnabled(true);
    cmbground.setEnabled(true);
    cmbmealclass.setEnabled(true);
    cmbconvoy.setEnabled(true);
    txtattendance.setEnabled(true);
    txtemail.setText("@gmail.com");
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
        
        
         PrinterJob pjob = PrinterJob.getPrinterJob();
            pjob.setJobName("SALE RECEIPT");
            pjob.setPrintable(new Printable(){ 
            public int print(Graphics pg ,PageFormat pf, int pagenum){
            pf.setOrientation(PageFormat.LANDSCAPE);
            if(pagenum > 0){
            return Printable.NO_SUCH_PAGE;
            }
            java.awt.Graphics2D g2 = (java.awt.Graphics2D)pg;
            g2.translate(pf.getImageableX(), pf.getImageableY());
            g2.scale(0.63, 0.97);
            jpreceipt.paint(g2);
            return Printable.PAGE_EXISTS;
            }
            });
            boolean  ok = pjob.printDialog();
            if(ok){
            try{
            pjob.print();
             
     /*btnsave.setEnabled(false);
    btnprint.setEnabled(false);
    btnrates.setEnabled(false);
    txtprice.setText("");
    txtprice.setEditable(false);
    txtdiscount.setText("");
    txtdiscount.setEditable(false);
    txtnetprice.setText("");
    txtnetprice.setEditable(false);
    txtid.setText("");
    txtid.setEnabled(false);
    txtphone.setText("");
    txtphone.setEnabled(false);
    txtemail.setText("");
    txtemail.setEnabled(false);
    
    jdwedding.setEnabled(false);
    cmbground.setEnabled(false);
    cmbmealclass.setEnabled(false);
    cmbconvoy.setEnabled(false);
    txtattendance.setText("");
    txtattendance.setEnabled(false);*/
     
            }catch(PrinterException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            }
    }//GEN-LAST:event_btnprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Weddingcontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Weddingcontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Weddingcontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Weddingcontrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Weddingcontrol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnapprovebook;
    private javax.swing.JButton btncancelbook;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnrates;
    private javax.swing.JButton btnreports;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cmbconvoy;
    private javax.swing.JComboBox<String> cmbground;
    private javax.swing.JComboBox<String> cmbmealclass;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdwedding;
    private javax.swing.JPanel jpreceipt;
    private javax.swing.JLabel lbdate;
    private javax.swing.JTextArea tareceipt;
    private javax.swing.JTextField txtattendance;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnetprice;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
